FROM node:24-alpine

ENV CI=true

WORKDIR /app

COPY package.json .npmrc pnpm-workspace.yaml ./

RUN corepack enable && pnpm install --ignore-scripts && pnpm approve-builds esbuild && pnpm install --ignore-scripts

COPY . .

EXPOSE 5173

CMD ["pnpm", "run", "dev", "--", "--host"]
